#!/usr/bin/env python3
"""Regenerates lib/icon_catalogue.dart from the installed Flutter SDK.

Flutter tree-shakes icon glyphs, which it can only do when every IconData is a
compile-time constant — so an icon picker cannot build IconData from a codepoint
read out of storage. Every icon it offers has to be named in source. That is why
this is generated rather than hand-written: the alternative was the eighteen
icons someone was willing to type.

Run after a Flutter upgrade:
    python3 tool/generate_icon_catalogue.py
"""

import pathlib
import re
import subprocess
import sys

SUFFIX = "_rounded"


def flutter_root() -> pathlib.Path:
    which = subprocess.run(["which", "flutter"], capture_output=True, text=True)
    if which.returncode != 0:
        sys.exit("flutter not found on PATH")
    return pathlib.Path(which.stdout.strip()).resolve().parent.parent


def main() -> None:
    icons_dart = (
        flutter_root() / "packages/flutter/lib/src/material/icons.dart"
    )
    if not icons_dart.exists():
        sys.exit(f"not found: {icons_dart}")

    pattern = re.compile(
        r"^\s*static const IconData ([a-z0-9_]+" + SUFFIX + r") = IconData\(",
        re.MULTILINE,
    )
    names = sorted(set(pattern.findall(icons_dart.read_text())))

    entries = []
    seen = set()
    for identifier in names:
        key = identifier[: -len(SUFFIX)]
        # A handful of real icons are themselves named "..._rounded", which
        # would collide with the stripped key of another. First wins; the loser
        # keeps its full name as its key so nothing is lost.
        if key in seen:
            key = identifier
        seen.add(key)
        entries.append((key, identifier))

    out = pathlib.Path(__file__).resolve().parent.parent / "lib/icon_catalogue.dart"
    body = "\n".join(f"  '{key}': Icons.{ident}," for key, ident in entries)
    out.write_text(
        f'''// GENERATED by tool/generate_icon_catalogue.py — do not edit by hand.
//
// Every Material icon the card picker can offer, in the rounded style the rest
// of the launcher uses. Generated because Flutter tree-shakes icon glyphs and
// can only do that when each IconData is a compile-time constant: an icon
// chosen at runtime still has to have been named in source somewhere.
//
// Keys are the icon name without its "_rounded" suffix, and are what gets
// stored on a card. Storing a name rather than a codepoint means a card keeps
// its icon across a Flutter upgrade that renumbers the font.

import 'package:flutter/material.dart';

const Map<String, IconData> materialIcons = <String, IconData>{{
{body}
}};
''',
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(out.parent.parent)} with {len(entries)} icons")


if __name__ == "__main__":
    main()
